article/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.views.generic import ListView,DetailView
from article.models import Article

urlpatterns = [
	url(r'^$',ListView.as_view(queryset = Article.objects.all().order_by('-time'),template_name = "article/articleList.html"),{'title':'Article'}),
	url(r'/(?P<pk>[-\w ]+)',views.ArticleDetailView.as_view(),name = 'article-detail')]

feed/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import logout

urlpatterns=[
	url(r'^$',views.index,name = 'index'),
	url(r'^login/$',views.login, name = 'login'),
	url(r'^logout/$',logout,name= 'logout'),
	url(r'^register/$',views.register, name = 'register'),
	url(r'^compose/$',views.compose,name = 'compose'),
	url(r'^ajax/articleLike/$',views.articleLike,name = 'article-like'),
	url(r'^redirect/$',views.redirect1,name = 'redirect')]

mysite2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import re_path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^',include('feed.urls')),
    re_path(r'^article',include('article.urls'))
]

article/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from jsonfield import JSONField
# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User,primary_key = True,on_delete = models.CASCADE)
	
@receiver(post_save,sender = User)
def create_user_profile(sender,instance,created,**kwrags):
	if created:
		Profile.objects.create(user = instance)

@receiver(post_save,sender = User)
def save_user_profile(sender,instance,**kwargs):
	instance.profile.save()	


class Activity(models.Model):
	LIKE = 'L'
	COMMENT = 'C'
	ACTIVITY_TYPES = (
		(LIKE,'Like'),
		(COMMENT,'Comment'))
	user = models.ForeignKey(User,on_delete = models.CASCADE)
	activity_type = models.CharField(max_length = 1,choices = ACTIVITY_TYPES)
	article = models.CharField(max_length = 30)
	time = models.DateTimeField()

class Article(models.Model):
	profile = models.ForeignKey(Profile,related_name = 'posted_by',on_delete = models.CASCADE)
	content = models.TextField()
	name = models.CharField(max_length = 50,primary_key = True)	
	time = models.DateTimeField()
	like = models.IntegerField(default = 0)
	comment = models.IntegerField(default = 0)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('article-detail',args = [self.name])

	def get_likes(self):
		likes = Activity.objects.all().filter(activity_type = 'L',article = self.name)
		return likes

	def calculate_likes(self):
		likes = self.get_likes()
		self.likes = likes.count()
		self.save()
		return self.likes

	def get_likers(self):
		likes = self.get_likes()
		likers = []
		for like in likes:
			likers.append(like.user)
		return likers


class Form(models.Model):
	name = models.CharField(max_length= 50)
	article = models.TextField()

feed/models.py
from django.db import models

# Create your models here.

class Feed(models.Model):
	user = models.CharField(max_length=50)
	time = models.DateTimeField()
	method = models.CharField(max_length = 50,null = True, blank = True)
	content = models.TextField()

	def __str__(self):
		return self.user

article/views.py
from django.shortcuts import render
from article.models import Article
from django.views.generic.detail import DetailView
from .models import Article

# Create your views here.
class ArticleDetailView(DetailView):
	model = Article
	
	def get_context_data(self,**kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = self.object.name
		return context	

feed/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login as auth_login,authenticate
from .models import Feed
from article.models import Article,Profile,Activity
from django.contrib.auth.forms import UserCreationForm
import datetime
from django.contrib.auth.models import User
from .post import Post
import jsonpickle
import json
from django.http import JsonResponse,HttpResponse
from django.views.decorators.csrf import csrf_protect

# Create your views here

def index(request):
	return render(request,'feed/feed.html',{'title':'Feeds','userData': Feed.objects.all().order_by('-time')})

def login(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username,password=password)
		if user is not None:
			if user.is_active:
				auth_login(request,user)
				now = datetime.datetime.now()
				method = 'login'
				text = "%s has joined the network" %username
				p = Feed(user=username,time=now,method = method, content =text)
				p.save()
				return redirect('/redirect')
		else:
			return redirect('/register')
	else:
		return render(request,'registration/login.html',{'title':'Login'})

def redirect1(request):
	return render(request,'registration/redirect.html')


def register(request):
	if request.method == "POST":
		'''print('hi')'''
		form = UserCreationForm(request.POST)

		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			user = authenticate(username = username, password = password)
			auth_login(request,user)
			now = datetime.datetime.now()
			method = 'login'
			text = "%s has joined the network" %username
			p = Feed(user=username,time=now,method = method, content =text)
			p.save()	
			return redirect('/')
	else:
		form = UserCreationForm()

	context = {'form': form,'title':'Register'}
	return render(request,'registration/register.html',context)

 
def compose(request):
	if request.user.is_authenticated:
		if request.method == "POST":
			form = Post(request.POST)
			if form.is_valid():
				name = form.cleaned_data['name']
				content = form.cleaned_data['article']
				time = datetime.datetime.now()
				method = 'article'
				username = request.user.username
				text = "%s has posted an article on %s" %(username,name)
				p = Feed(user=username,time=time,method = method, content =text)
				p.save()
				user = User.objects.get(id = request.user.id)
				profile = Profile.objects.get(user = user)
				a = Article(profile = profile,name = name, time = time,content = content)
				a.save()
				return redirect('/')

		else:
			form = Post()
			return render (request,'article/post.html',{'form':form,'title':'Post'})

	else:
		return redirect('/login')

@csrf_protect
def articleLike(request):
	article_id = request.POST.get('id')
	article = Article.objects.get(name = article_id)
	like = Activity.objects.filter(user = request.user, activity_type = Activity.LIKE, article = article.name) 
	if like:
		like.delete()
				
	else:
		like = Activity(user = request.user, activity_type = Activity.LIKE, article = article.name,time = datetime.datetime.now())
		like.save()
	return JsonResponse({'status':'ok'})
	

feed/templates/article/article.html
{% extends "feed/basic.html" %}

{% block content1 %}
{% endblock %}

{% block content %}
	{% for post in object_list %}
		<h5>{{post.time}}<a href="/article/{{post.name}}">{{post.name}}</a></h5>
	{% endfor %}
{% endblock %}

feed/templates/article/articleList.html
{% extends "feed/basic.html" %}

{% block content1 %}
{% endblock %}

{% block content %}
	<div class="list-group mt-3">
        <a href="/" class="list-group-item list-group-item-action list-group-item-dark"><h3>Articles</h3></a>
            {% for u in object_list %}              
                <a href="{{ u.get_absolute_url }}" class="list-group-item list-group-item-action"><p><b>{{u.name}}</b> {{u.time}}</p></a>
            {% endfor %}
    </div>
{% endblock %}

feed/templates/article/article_detail.html
{% extends "feed/basic.html" %}


{% block javascript %}
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	{% load staticfiles %}
	<script src= {% static "js/jquery.cookie.js" %} type="text/javascript"></script>
<script type="text/javascript">
	var csrftoken = $.cookie('csrftoken');
	function csrfSafeMethod(method){
		return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
	}
	$.ajaxSetup({
		beforeSend : function (xhr,settings) {
			if(!csrfSafeMethod(settings.type)&&!this.crossDomain){
				xhr.setRequestHeader("X-CSRFToken",csrftoken);
			}
		}
	});
	$(document).ready(function(){
			{% if user in article.get_likers %}
				$("a.like").data('action','Unlike');
				$("a.like").text('Unlike');
			{% else %}
				$("a.like").data('action','like');
				$("a.like").text('Like');
			{% endif %}	
		$("a.like").click(function(e){
			e.preventDefault();
			console.log('hi');
			$.post('{% url 'article-like' %}',{
				id : $(this).data('id')
			},
			function(data){
					if(data["status"]=="ok"){
					var previous_action = $("a.like").data('action');
					$("a.like").data('action',previous_action == 'like' ? 'Unlike':'like');
					$("a.like").text(previous_action == 'like'? 'unlike' : 'like');
					var previous_likes = parseInt($('span.count .total').text());
                    $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
					console.log('Hi again');
				}
				});
		});
	});
	</script>
	{% endblock %}
	{% block content1 %}
	{% endblock %}
{% block content %}
	<div class="mt-3">
		<h3>{{article.name}}</h3>
		<h6>on {{article.time}}</h6>
		{{article.content|safe|linebreaks}}
       <span class="count">
           <span class="total">{{ article.calculate_likes }}</span>
       </span>
        <a href="#" data-id="{{ article.name }}" data-action="" class="like">Like</a>
	</div>
{% endblock %}

feed/templates/article/post.html
{% extends "feed/basic.html" %}

{% block content1 %}
{% endblock %}

{% block content %}
	<form method="post" action="{% url 'compose' %}">
		{% csrf_token %}
		{% if form.errors %}
			<p>There's some error</p>
		{% endif %}

		{{form.as_p}}

		<button id="post" lass= "btn btn-lg btn-primary" type="submit" value="submit">post</button>
	</form>
{% endblock %}

{% block script %}
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script type="text/javascript">
			var socket = new WebSocket('ws://'+window.location.host+'/');
			socket.onclose = function(){
				console.log("hello");
			};

			$("#post").click(function(){
				var message = $("#id_name").val();
				console.log(message);
				socket.send(JSON.stringify({
					'user' : '{{user}}',
					'activity_type' : 'post',
					'message' : message
				}));
				console.log(socket);
			});
	</script>
{% endblock %}

feed/templates/feed/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{title}}</title>
  <meta charset="utf-8">
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'feed/css/bootstrap.min.css' %}">
  {% block javascript %}
  {% endblock %}
</head>
<body>
      <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Feeds</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/article">Articles</a>
            </li>
        </ul>
      </nav>
      <div class="container-fluid">
        {% block content1 %}
          <div class="row justify-content-end">
            <div class="col-2">
                <a href="/compose" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Post</a>
            </div>
            <div class="col-2">
              {% if user.is_authenticated %}
                <p>Logged in as {{user.username}}</p>
                <a href="/logout" class="btn btn-primary btn-sm active">Logout</a>
              {% else %}
                <p>You are not logged in</p>
                <a href="/login" class="btn btn-primary btn-sm active">Login</a>
              {% endif %}
            </div>
          </div>
        {% endblock %}
      </div>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-6">
              {% block content %}
              {% endblock %}
          </div>
        </div> 
      </div>
</body>
{% block script %}
{% endblock %}
</html>

feed/templates/feed/feed.html
{% extends "feed/basic.html" %}

{% block content %}
	<div class="list-group">
        <a href="/" id="list" class="list-group-item list-group-item-action list-group-item-dark"><h3>Feeds</h3></a>
            {% for u in userData %}              
                <a href="{% if u.method == 'login' %}/{% else %}/article{% endif %}" class="list-group-item list-group-item-action"><p><b>{{u.user}}</b> {{u.time}}{{u.content}}</p></a>
            {% endfor %}
    </div>
{% endblock %} 
{% block script %}
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script type="text/javascript">
			var socket = new WebSocket('ws://'+window.location.host+'/');
			socket.onclose = function(){
				console.log('connection rejected');
			};
			socket.onmessage = function(e){
				var data = JSON.parse(e.data);
				var user = data['user'],message = data['message'];
				console.log(data['activity_type']);
				if(data['activity_type']=='login'){
					var content = '<a class="list-group-item list-group-item-action"><p><b>'+user+'</b> has logged in</p></a>';
					$("#list").append(content);
				}
				else{
					var article = '<a class="list-group-item list-group-item-action"><p><b>'+user+'</b> has posted an article on '+message+'</p></a>';
					$("#list").append(article);
				}
				
			};
	</script>
{% endblock %}